name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version
          
      - name: Install dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress --save-dev
          
      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    needs: cypress-tests
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '18'
    
      - name: Install Newman
        run: npm install -g newman
    
      - name: Create API test directory
        run: mkdir -p api-test-results
    
      - name: Run API tests
        run: |
          npx newman run api-tests/collection/api-tests.postman_collection.json \
          -e api-tests/collection/Grocery-Store-Env.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export api-test-results/newman-results.json
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
         name: api-test-results
         path: api-test-results/newman-results.json

  performance-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install k6 (updated method)
        run: |
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D78C6C76840E5B984
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          
      - name: Run performance tests
        working-directory: ./performance-tests
        run: k6 run order-creation-test.js