name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version
          
      - name: Install dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress --save-dev
          
      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    needs: cypress-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Newman
        run: npm install -g newman
        
      - name: Run API tests with Newman
        run: |
          cd api-tests
          npx newman run ./collection/api-tests.postman_collection.json \
          -e ./collection/Grocery-Store-Env.postman_environment.json \
          -n 1 \
          --reporters cli,json \
          --reporter-json-export results.json
          
      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: newman-test-results
          path: api-tests/results.json

  performance-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install k6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
          echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install k6
          
      - name: Run performance tests
        run: |
          cd performance-tests
          k6 run order-creation-test.js