name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          
      - name: Install dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress --save-dev
          
      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '18'
    
      - name: Install Newman
        run: npm install -g newman
    
      - name: Create API test directory
        run: mkdir -p api-test-results
    
      - name: Run API tests
        run: |
          npx newman run api-tests/collection/api-tests.postman_collection.json \
          -e api-tests/collection/Grocery-Store-Env.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export api-test-results/newman-results.json
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
         name: api-test-results
         path: api-test-results/newman-results.json

  performance-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v3

      - name: Install k6 (guaranteed working method)
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          wget https://github.com/grafana/k6/releases/download/v0.50.0/k6-v0.50.0-linux-amd64.deb
          sudo dpkg -i k6-v0.50.0-linux-amd64.deb || sudo apt-get install -f -y
          k6 version  # Verify installation

      - name: Run performance tests
        working-directory: ./performance-tests
        run: k6 run order-creation-test.js