name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          
      - name: Install dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress --save-dev
          
      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '18'
    
      - name: Install Newman
        run: npm install -g newman
    
      - name: Create API test directory
        run: mkdir -p api-test-results
    
      - name: Run API tests
        run: |
          npx newman run api-tests/collection/api-tests.postman_collection.json \
          -e api-tests/collection/Grocery-Store-Env.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export api-test-results/newman-results.json
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
         name: api-test-results
         path: api-test-results/newman-results.json

  performance-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install k6
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
        echo "deb https://dl.bintray.com/loadimpact/deb stable main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Run Load Test
      run: k6 run tests/order/order-load-test.js

    - name: Run Spike Test
      run: k6 run tests/order/order-spike-test.js

    - name: Run Soak Test (short version)
      run: k6 run tests/order/order-soak-test.js --duration 5m

    - name: Run Stress Test
      run: k6 run tests/order/order-stress-test.js

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v3
      with:
        name: performance-reports
        path: reports/