name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
          
      - name: Install dependencies
        working-directory: ./ui-tests
        run: |
          npm install
          npm install cypress --save-dev
          
      - name: Run Cypress tests
        working-directory: ./ui-tests
        run: npx cypress run

  api-tests:
    runs-on: ubuntu-latest
    needs: ui-tests
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: '18'
    
      - name: Install Newman
        run: npm install -g newman
    
      - name: Create API test directory
        run: mkdir -p api-test-results
    
      - name: Run API tests
        run: |
          npx newman run api-tests/collection/api-tests.postman_collection.json \
          -e api-tests/collection/Grocery-Store-Env.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export api-test-results/newman-results.json
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
         name: api-test-results
         path: api-test-results/newman-results.json

  performance-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install latest k6 (with full ES6 support)
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates gnupg
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6
        k6 version

    - name: Run tests
      run: |
        cd performance-tests
        k6 run tests/order/order-load-test.js
        k6 run tests/order/order-spike-test.js
        k6 run tests/order/order-soak-test.js --duration 5m
        k6 run tests/order/order-stress-test.js

    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: performance-reports
        path: performance-tests/reports/